#!/usr/bin/perl

use strict;

sub dodir($) {
  my $dir = shift;

  opendir(IN, $dir) || die("$dir: $!\n");
  my @dir = readdir IN;
  closedir IN;

  foreach my $i (@dir) {
    next if($i eq ".");
    next if($i eq "..");
    if($i =~ /\.dso$/ || $i =~ /\.lib$/) {
      if($i =~ /\{000a0000\}\./) {
        my $new = $i;
        $new =~ s/\{000a0000\}//;
        symlink($i, "$dir/$new") unless -e "$dir/$new";
      } else {
        my $new = $i;
        $new =~ s/\.dso/\{000a0000\}$&/;
        $new =~ s/\.lib/\{000a0000\}$&/;
        symlink($i, "$dir/$new") unless -e "$dir/$new";
      }
    }
  }

}

die("Usage: fixlib dir\n") if(@ARGV != 1);
dodir($ARGV[0]);
