#!/bin/sh

if test $# != 2 -a $# != 3 -o $0 != "./install_gnupoc_s60_31"; then
  echo "Usage: ./install_gnupoc_s60_31 <path-to-sdk-zip> <target-dir>"
  echo " e.g.: ./install_gnupoc_s60_31 S60-SDK-200634-3.1-Cpp-f.1090b.zip ~/symbian-sdks/s60_31"
  exit 1
fi

SRC=$1
DEST=`echo $2 | sed s:/\$::`

mkdir -p $DEST

while read a
do
  echo "$a"
  sh -c "$a"
  if test $? != 0; then
    echo "Unexcpected error: aborting."
    exit 1
  fi
done << __END

### Unzip & Copy selected files
mkdir _e
unzip -qn $SRC -d _e

mkdir epoc32
cd epoc32; wine ../i6comp.exe x -gEpoc32 ../_e/data2.cab > /dev/null
mv epoc32 $DEST

wine i6comp.exe x -gicon _e/data2.cab > /dev/null
mv s60.ico $DEST

mkdir series60doc
cd series60doc; wine ../i6comp.exe x -gSeries60Doc ../_e/data2.cab > /dev/null
mv series60doc $DEST

mkdir series60tools
cd series60tools; wine ../i6comp.exe x -gSeries60Tools ../_e/data2.cab > /dev/null
mv series60tools $DEST

unzip -qn _e/Examples.zip
mv Examples $DEST/examples
mv S60Ex $DEST/s60ex

### Fixing
./lowercase $DEST/epoc32/tools
./lowercase $DEST/epoc32/include
./lowercase $DEST/epoc32/release
./lowercase $DEST/epoc32/data
./fixinclude $DEST/epoc32/include
./lowercase $DEST/s60ex
./fixinclude $DEST/s60ex
./fixexamples $DEST/s60ex
./lowercase $DEST/examples
./fixinclude $DEST/examples
./fixexamples $DEST/examples
find $DEST/epoc32/tools -name \*.pl -or -name \*.pm | xargs -n 1 recode dos..latin1
cp -a $DEST/epoc32/tools $DEST/epoc32/tools_orig
cat gnupoc-s60_31-patch | (cd $DEST/epoc32; patch -p0 )
cd $DEST/epoc32/tools; chmod a+x *.pl bldmake abld makmake bmconv rcomp makesis epoc eshell petran pfsdump setupcomms elf2e32 mifconv makekeys signsis

rm -rf _e

__END

exit 0
