CXXFLAGS = -Ilibelf/include -DNO_ELF_RAWCHUNK
LDFLAGS = -Llibelf/lib

include Makefile

libelf.a: libelf/lib/libelf.a

libelf/lib/libelf.a:
	cd libelf-elftoolchain && make install PREFIX=`pwd`/../libelf

