#!/usr/bin/perl

use strict;

sub dodir($);

sub dodir($) {
  my $dir = shift;

  #print "DIR: $dir\n";

  opendir IN, $dir;
  my @dir = readdir IN;
  closedir IN;

  foreach my $i (@dir) {
    next if($i eq ".");
    next if($i eq "..");
    next if($i =~ /\.jpg/);
    next if($i =~ /\.bmp/);
    next if($i =~ /\.mbm/);
    next if($i =~ /\.gif/);
    next if($i =~ /\.wav/);
    next if(-l "$dir/$i");

    if(-d "$dir/$i") {
      dodir("$dir/$i");
    } else {
      #print "FILE: $dir/$i\n";
      open FHIN,"$dir/$i" || die("Can't read $dir/$i");
      open FHOUT,">$dir/$i.out" || die("Can't write to $dir/$i.out");

      while(my $line = <FHIN>) {
        if($line =~ m/^#include/) {
	  my @values = split('//', $line);
	  $values[0] =~ tr [A-Z\\] [a-z/];
	  $values[0] =~ s/gles\//GLES\//;
	  $values[0] =~ s/gles2\//GLES2\//;
	  $values[0] =~ s/egl\//EGL\//;
	  $values[0] =~ s/product_include/PRODUCT_INCLUDE/;

	  $line = join('//', @values);
	}
	$line =~ s/[\r\n]//g;
	print FHOUT "$line\n";
      }

      close(FHIN);
      close(FHOUT);
      unlink "$dir/$i";
      rename "$dir/$i.out", "$dir/$i";
    }
  }
}

die("Usage: fixinclude dir\n") if(@ARGV != 1);
dodir($ARGV[0]);
