#!/bin/sh

if test $# != 2 -o $0 != "./install_gnupoc_s60_21"; then
  echo "Usage: ./install_gnupoc_s60_21 <path-to-sdk-zip> <target-dir>"
  echo " e.g.: ./install_gnupoc_s60_21 S60_SDK_2_1_NET.zip ~/symbian-sdks/s60_21"
  exit 1
fi

SRC=$1
DEST=`echo $2 | sed s:/\$::`

mkdir -p $DEST

while read a
do
  echo "$a"
  sh -c "$a"
  if test $? != 0; then
    echo "Unexpected error: aborting."
    exit 1
  fi
done << __END

### Unzip & Copy selected files
unpack21/unpack21.sh $SRC

mv target/Series60_v21/Debug $DEST/debug
mv target/Series60_v21/Epoc32 $DEST/epoc32
mv target/Series60_v21/Examples $DEST/examples
mv target/Series60_v21/Series60Ex $DEST/series60ex
mv target/Series60_v21/Series60Doc $DEST/series60doc
mv target/Series60_v21/Series60Tools $DEST/series60tools
rm -rf target

### Fixing
./lowercase $DEST/epoc32/tools
./lowercase $DEST/epoc32/include
./lowercase $DEST/epoc32/release
./lowercase $DEST/epoc32/data
./fixinclude $DEST/epoc32/include
./lowercase $DEST/series60ex
./fixinclude $DEST/series60ex
./fixexamples $DEST/series60ex
./lowercase $DEST/examples
./fixinclude $DEST/examples
./fixexamples $DEST/examples
for i in \`find $DEST/epoc32/tools -name \\\*.pl -or -name \\\*.pm\`; do ./dos2unix \$i; done
cp -pR $DEST/epoc32/tools $DEST/epoc32/tools_orig
cat gnupoc-s60_21-patch | (cd $DEST/epoc32; patch -p0 )
find $DEST/epoc32/tools -name \\\*.orig -exec rm {} \\\\;
cd $DEST/epoc32/tools; chmod a+x \*.pl bldmake abld makmake bmconv rcomp makesis epoc eshell petran pfsdump setupcomms makekeys extmake

__END

exit 0
