#!/bin/sh

if test $# != 2 -o $0 != "./install_gnupoc_s60_20"; then
  echo "Usage: ./install_gnupoc_s60_20 <path-to-sdk-zip> <target-dir>"
  echo " e.g.: ./install_gnupoc_s60_20 s60_sdk_v2_0.zip ~/symbian-sdks/s60_20"
  exit 1
fi

SRC=$1
DEST=`echo $2 | sed s:/\$::`

mkdir -p $DEST

export PATH=unshield:$PATH

while read a
do
  echo "$a"
  sh -c "$a"
  if test $? != 0; then
    echo "Unexcpected error: aborting."
    exit 1
  fi
done << __END

### Unzip & Copy selected files
mkdir _e
unzip -qn $SRC -d _e

unshield -g Epoc32 x _e/data2.cab
mv Epoc32 $DEST/epoc32

unshield -g Examples x _e/data2.cab
mv Examples $DEST/examples

unshield -g SymbianSampleCode x _e/data2.cab
mv SymbianSampleCode $DEST/symbiansamplecode

unshield -g Series60Ex x _e/data2.cab
mv Series60Ex $DEST/series60ex

unshield -g Series60Doc x _e/data2.cab
mv Series60Doc $DEST/series60doc

unshield -g Series60Tools x _e/data2.cab
mv Series60Tools $DEST/series60tools


### Fixing
./lowercase $DEST/epoc32/tools
./lowercase $DEST/epoc32/include
./lowercase $DEST/epoc32/release
./lowercase $DEST/epoc32/data
./fixinclude $DEST/epoc32/include
./lowercase $DEST/series60ex
./fixinclude $DEST/series60ex
./fixexamples $DEST/series60ex
./lowercase $DEST/examples
./fixinclude $DEST/examples
./fixexamples $DEST/examples
for i in \`find $DEST/epoc32/tools -name \*.pl -or -name \*.pm\`; do tr -d '\\\\r' < \$i > \$i.tmp; mv \$i.tmp \$i; done
cp -pR $DEST/epoc32/tools $DEST/epoc32/tools_orig
cat gnupoc-s60_20-patch | (cd $DEST/epoc32; patch -p0 )
find $DEST/epoc32/tools -name *.orig | xargs rm
cd $DEST/epoc32/tools; chmod a+x *.pl bldmake abld makmake bmconv rcomp makesis epoc eshell petran pfsdump setupcomms makekeys extmake

rm -rf _e

__END

exit 0
