#!/bin/sh

if test $# != 2 -o $0 != "./install_gnupoc_s60_31"; then
  echo "Usage: ./install_gnupoc_s60_31 <path-to-sdk-zip> <target-dir>"
  echo " e.g.: ./install_gnupoc_s60_31 S60-SDK-200634-3.1-Cpp-f.1090b.zip ~/symbian-sdks/s60_31"
  exit 1
fi

SRC=$1
DEST=`echo $2 | sed s:/\$::`

mkdir -p $DEST

export PATH=unshield:$PATH

while read a
do
  echo "$a"
  sh -c "$a"
  if test $? != 0; then
    echo "Unexcpected error: aborting."
    exit 1
  fi
done << __END

### Unzip & Copy selected files
mkdir _e
unzip -qn $SRC -d _e

unshield x -g Epoc32 _e/data2.cab
mv Epoc32 $DEST/epoc32

unshield x -g icon _e/data2.cab
mv icon/s60.ico $DEST
rmdir icon

unshield x -g Series60Doc _e/data2.cab
mv Series60Doc $DEST/series60doc

unshield x -g Series60Tools _e/data2.cab
mv Series60Tools $DEST/series60tools

unzip -qn _e/Examples.zip
mv Examples $DEST/examples
mv S60Ex $DEST/s60ex

### Fixing
./lowercase $DEST/epoc32/tools
./lowercase $DEST/epoc32/include
./lowercase $DEST/epoc32/release
./lowercase $DEST/epoc32/data
./fixinclude $DEST/epoc32/include
./lowercase $DEST/s60ex
./fixinclude $DEST/s60ex
./fixexamples $DEST/s60ex
./lowercase $DEST/examples
./fixinclude $DEST/examples
./fixexamples $DEST/examples
for i in \`find $DEST/epoc32/tools -name \*.pl -or -name \*.pm\`; do j=\`tempfile\`; tr -d '\\\\r' < \$i > \$j; mv \$j \$i; done
cp -a $DEST/epoc32/tools $DEST/epoc32/tools_orig
cat gnupoc-s60_31-patch | (cd $DEST/epoc32; patch -p0 )
cd $DEST/epoc32/tools; chmod a+x *.pl bldmake abld makmake bmconv rcomp makesis epoc eshell petran pfsdump setupcomms elf2e32 mifconv makekeys signsis extmake

rm -rf _e

__END

exit 0
