#!/bin/sh

if [ $# != 2 -a $# != 3 -o $0 != "./install_gcc_539" ]; then
  echo "Usage: ./install_gcc_539 <path-to-sdk-zip> <target-dir>"
  echo " e.g.: ./install_gcc_539 gcc-539-2aeh-source.tar.bz2 ~/symbian-gcc"
  exit 1
fi

SRC=$1
DEST=`echo $2 | sed s:/\$::`

mkdir -p $DEST

MAKE=make
if [ "`which gmake`" != "" ]; then
        MAKE=gmake
fi

cpp=`which cpp`
if [ ! -e $DEST/bin/cpp ] && [ "`file $cpp | grep 'shell script'`" != "" ]; then LINK_CPP=1; fi

while read a
do
  echo "$a"
  sh -c "$a"
  if test $? != 0; then
    echo "Unexpected error: aborting."
    exit 1
  fi
done << __END

tar -jxvf $SRC
patch -p0 < gcc-539.patch
mkdir obj
cd obj; sh ../src/configure --prefix=$DEST --target=arm-epoc-pe; 
cd obj; if [ "`uname -m`" = "x86_64" ]; then sed s/-O2// Makefile > tmp; mv tmp Makefile; fi
cd obj; $MAKE all-binutils all-gas all-ld all-gcc
cd obj; $MAKE install-binutils install-gas install-ld install-gcc
rm -rf obj
rm -rf src
cp arm-specs $DEST/lib/gcc-lib/arm-epoc-pe/2.9-psion-98r2/specs
cd $DEST/bin; if [ ! -e arm-epoc-pe-cpp ]; then ln -s ../lib/gcc-lib/arm-epoc-pe/2.9-psion-98r2/cpp arm-epoc-pe-cpp; fi
cd $DEST/bin; if [ ! -e as ]; then ln -s arm-epoc-pe-as as; fi
if [ "$LINK_CPP" != "" ]; then cd $DEST/bin; ln -s arm-epoc-pe-cpp cpp; fi

__END

