#!/bin/sh

if [ $# != 1 -o $0 != "./install_eka1_tools" ]; then
  echo "Usage: ./install_eka1_tools <target-dir>"
  echo " e.g.: ./install_eka1_tools ~/symbian-gcc"
  exit 1
fi

DEST=`echo $1 | sed s:/\$::`

mkdir -p $DEST/bin

MAKE=make
if [ "`which gmake`" != "" ]; then
	MAKE=gmake
fi

TRUE=`which true`

while read a
do
  echo "$a"
  sh -c "$a"
  if test $? != 0; then
    echo "Unexpected error: aborting."
    exit 1
  fi
done << __END

cd petran-1.1.0 && $MAKE && cp petran/petran e32uid/uidcrc $DEST/bin
cd makesis-2.0.0 && $MAKE && cp src/makesis $DEST/bin
cd bmconv-1.1.0-2 && $MAKE && cp src/bmconv $DEST/bin
cd rcomp-7.0.1 && $MAKE && cp src/rcomp $DEST/bin
gcc genaif.c -o $DEST/bin/genaif
g++ aiftool.cpp -o $DEST/bin/aiftool

cd make-3.81 && ./configure && $MAKE && cp make $DEST/bin/extmake
g++ mifconv.cpp -o $DEST/bin/mifconv
ln -sf $TRUE $DEST/bin/rem
cp del $DEST/bin
cp copy $DEST/bin


__END

